name: CI

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "**"
  schedule:
    # Nightly tests run on master by default:
    #   Scheduled workflows run on the latest commit on the default or base branch.
    #   (from https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule)
    - cron: "0 7 * * 1"


jobs:
  test:
    runs-on: ${{ matrix.cfg.os }}
    strategy:
      fail-fast: false
      matrix:
        cfg:
          # Teste auf Linux mit verschiedenen PyTorch-Versionen
          - { os: ubuntu-latest, python-version: '3.12', extra: 'cpu' }
          - { os: ubuntu-latest, python-version: '3.12', extra: 'cu124' }
          - { os: ubuntu-latest, python-version: '3.12', extra: 'cu126' }

          # Teste zusätzlich auf macOS mit der CPU-Version
          - { os: macos-latest, python-version: '3.12', extra: 'cpu' }

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

#      - name: Install h5py separately to debug
#        if: runner.os == 'macOS'
#        shell: bash -el {0}
#        run: uv pip install "h5py==3.11.0"

      - name: Install dependencies with ${{ matrix.cfg.extra }} extra
        shell: bash -el {0}
        run: uv sync --extra ${{ matrix.cfg.extra }}

      - name: Run unit tests
        shell: bash -el {0}
        run: |
          source .venv/bin/activate
          uv run pytest tests

      - name: Run integration tests
        shell: bash -el {0}
        run: |
          source .venv/bin/activate
          # Führe Integrationstests je nach extra aus
          if [[ "${{ matrix.cfg.extra }}" == "cpu" ]]; then
            lettuce --no-cuda convergence --use-no-cuda_native
            lettuce --no-cuda benchmark --use-no-cuda_native
          else
            lettuce --no-cuda convergence --use-no-cuda_native
            lettuce --no-cuda benchmark --use-no-cuda_native
          fi


#      - name: Setup Miniconda
#        uses: conda-incubator/setup-miniconda@v3.0.4
#        with:
#          python-version: ${{ matrix.cfg.python-version }}
#      - name: Install dependencies
#        shell: bash -el {0}  # specifying shell to make sure the conda environment and installations are still active
#        run: |
#          conda install "${{ matrix.cfg.torch-version }}" -c pytorch -c nvidia
#          conda install --file requirements.txt -c conda-forge -c pytorch -c nvidia
#      - name: Install lettuce
#        shell: bash -el {0}
#        run: |
#          pip install --use-pep517 .
#      - name: Unit tests with pytest
#        shell: bash -el {0}
#        run: |
#          pytest tests
#      - name: Integration tests
#        shell: bash -el {0}
#        run: |
#          lettuce --no-cuda convergence --use-no-cuda_native
#          lettuce --no-cuda benchmark --use-no-cuda_native
